/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.gui.joingame;

import com.connutils.Request;
import com.gui.general.Requestable;
import com.conn.Client;
import com.connutils.Action;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.gui.principalframe.PrincipalFrame;
import com.gui.lobby.LobbyBuilder;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author migue
 */
public class JoinGame extends javax.swing.JPanel implements Requestable{

    /**
     * Creates new form CreateGame
     */
    
    PrincipalFrame principalFrame;
    
    private List<Action> actions = new ArrayList<Action>(){{
        add(new ActionJoined(JoinGame.this));
    }};
    
    public JoinGame(PrincipalFrame principalFrame) {
        initComponents();
        this.principalFrame = principalFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lobbyNameLabel = new javax.swing.JLabel();
        lobbyTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        lobbyNameLabel.setText("Nombre de sala: ");

        createButton.setText("CREAR");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(createButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lobbyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lobbyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lobbyNameLabel)
                    .addComponent(lobbyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addComponent(createButton)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if (tryToCreateGame()) {
            //CARGANDO...
        }else{
            JOptionPane.showMessageDialog(this, "Valores mal asignados");
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private boolean tryToCreateGame() {
        String nameText = this.lobbyTextField.getText();
        
        if(nameText.isBlank()) return false;
        
        Request createGameRequest = new Request("join");
        createGameRequest.put("name", nameText);
        
        try {
            Client.sendRequest(createGameRequest);
            return true;
        } catch (JsonProcessingException ex) {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel lobbyNameLabel;
    private javax.swing.JTextField lobbyTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void gotRequest(Request request) {
        actions.stream().filter(action -> action.getType().equals(request.getHeader())).forEach(action -> action.execute(request));
    }
    
    void joined(Request request){
        principalFrame.setUpGame(
                    LobbyBuilder
                            .createLobby(principalFrame, request)
                            .build()
        );
    }

    
}
